# Generated by Django 5.1 on 2024-08-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('calificacion', models.IntegerField()),
                ('aceptacion', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=100)),
                ('especificaciones_tecnicas', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('opinion_sin_definir', models.TextField(blank=True, null=True)),
                ('opinion_positiva', models.TextField(blank=True, null=True)),
                ('opinion_negativa', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
